vich_uploader:
    db_driver: orm

    mappings:
       product_image:
           uri_prefix: /profileimages
           upload_destination: '%kernel.project_dir%/public/profileimages'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
